## 1. Carregamento e Visualização dos Dados

In [1]:
import pandas as pd
import numpy as np
from itertools import product
from collections import defaultdict

URL = "https://docs.google.com/spreadsheets/d/1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg/export?format=csv"
df_raw = pd.read_csv(URL)

print(f"Shape: {df_raw.shape}")
df_raw.head(3)

Shape: (186, 11)

,Carimbo de data/hora,Você ficou gripado no ano passado ?,Você tomou vacina da gripe no ano passado?,"Você frequentou no ano passado, semanalmente ambientes com muitas pessoas? (salas cheias, ônibus, eventos, etc.)",Você viajou no ano passado mais de 100 km de distância?,"Você tem alergia nas vias aéreas (rinite, sinusite, etc.)?",Quantas horas você dormiu em média por noite no ano passado?,Você praticou atividade física no ano passado?,Você se alimentou de forma balanceada no ano passado?,"Em média, quantas vezes você lavou as mãos por dia no ano passado?","Na sua percepção, o seu nível de estresse no ano passado foi:"
0,24/03/2026 15:01:35,Sim,Sim,Sim,Poucas vezes por ano,Médio,4 horas ou menos,Sim,Às vezes,3 a 5 vezes,5.0
1,24/03/2026 15:04:20,Sim,Sim,Sim,Nuca,Não,entre 4 e 6 horas,Não,"Não, raramente",Mais de 10 vezes,3.0
2,24/03/2026 15:04:20,Sim,Não,Sim,Poucas vezes por ano,Pouco,mais de 6 horas,Sim,Às vezes,6 a 10 vezes,3.0

In [2]:
# Renomear colunas para nomes curtos
col_map = {
    df_raw.columns[0]: 'timestamp',
    df_raw.columns[1]: 'gripado',
    df_raw.columns[2]: 'vacina',
    df_raw.columns[3]: 'ambientes_cheios',
    df_raw.columns[4]: 'viagem',
    df_raw.columns[5]: 'alergia',
    df_raw.columns[6]: 'horas_sono',
    df_raw.columns[7]: 'atividade_fisica',
    df_raw.columns[8]: 'alimentacao',
    df_raw.columns[9]: 'lavagem_maos',
    df_raw.columns[10]: 'estresse',
}

df = df_raw.rename(columns=col_map).drop(columns=['timestamp'])
print("Colunas:", df.columns.tolist())
print(f"\nTotal de instâncias: {len(df)}")
df.head()

Colunas: ['gripado', 'vacina', 'ambientes_cheios', 'viagem', 'alergia', 'horas_sono', 'atividade_fisica', 'alimentacao', 'lavagem_maos', 'estresse']

Total de instâncias: 186

,gripado,vacina,ambientes_cheios,viagem,alergia,horas_sono,atividade_fisica,alimentacao,lavagem_maos,estresse
0,Sim,Sim,Sim,Poucas vezes por ano,Médio,4 horas ou menos,Sim,Às vezes,3 a 5 vezes,5.0
1,Sim,Sim,Sim,Nuca,Não,entre 4 e 6 horas,Não,"Não, raramente",Mais de 10 vezes,3.0
2,Sim,Não,Sim,Poucas vezes por ano,Pouco,mais de 6 horas,Sim,Às vezes,6 a 10 vezes,3.0
3,Sim,Não,Não,Nuca,Muito,mais de 6 horas,Sim,Às vezes,2 vezes ou menos,2.0
4,Sim,Sim,Sim,Pelo menos uma vez por mês,Médio,entre 4 e 6 horas,Não,Às vezes,6 a 10 vezes,4.0

In [3]:
# Distribuição da classe alvo
print("Distribuição da classe alvo 'gripado':")
print(df['gripado'].value_counts())
print()
print("Distribuição em percentual:")
print(df['gripado'].value_counts(normalize=True).map('{:.1%}'.format))

Distribuição da classe alvo 'gripado':
gripado
Sim    109
Não     77
Name: count, dtype: int64

Distribuição em percentual:
gripado
Sim    58.6%
Não    41.4%
Name: proportion, dtype: object

## 2. Pré-processamento

Antes de rodar o PRISM, vamos:
1. Remover linhas com valores ausentes
2. Garantir que todos os atributos sejam categóricos (strings)
3. Separar features da classe alvo

In [4]:
df_clean = df.dropna().copy()

# Garantir tipos string em todos os atributos
for col in df_clean.columns:
    df_clean[col] = df_clean[col].astype(str).str.strip()

# Normalizar atributo estresse: remover ".0" para deixar como inteiro legível
df_clean["estresse"] = df_clean["estresse"].str.replace(r"\.0$", "", regex=True)

print(f"Instâncias após limpeza: {len(df_clean)}")
print()

# Verificar valores únicos por atributo
for col in df_clean.columns:
    vals = df_clean[col].unique()
    print(f"  {col}: {sorted(vals)}")

Instâncias após limpeza: 185

  gripado: ['Não', 'Sim']
  vacina: ['Não', 'Sim']
  ambientes_cheios: ['Não', 'Sim']
  viagem: ['Nuca', 'Pelo menos uma vez por mês', 'Poucas vezes por ano']
  alergia: ['Muito', 'Médio', 'Não', 'Pouco']
  horas_sono: ['4 horas ou menos', 'entre 4 e 6 horas', 'mais de 6 horas']
  atividade_fisica: ['Não', 'Sim']
  alimentacao: ['Não, raramente', 'Sim, a maior parte do tempo', 'Às vezes']
  lavagem_maos: ['2 vezes ou menos', '3 a 5 vezes', '6 a 10 vezes', 'Mais de 10 vezes']
  estresse: ['1', '2', '3', '4', '5']

In [5]:
# Separar features e classe
features = [c for c in df_clean.columns if c != 'gripado']
target = 'gripado'
classes = df_clean[target].unique().tolist()

print(f"Atributos ({len(features)}): {features}")
print(f"Classes: {classes}")

Atributos (9): ['vacina', 'ambientes_cheios', 'viagem', 'alergia', 'horas_sono', 'atividade_fisica', 'alimentacao', 'lavagem_maos', 'estresse']
Classes: ['Sim', 'Não']

## 3. Implementação do Algoritmo PRISM

### Lógica principal

Para cada **classe alvo** $c$:
1. Comece com antecedente vazio e conjunto completo de dados
2. Para cada par (atributo, valor), calcule $p(c \mid atributo = valor)$
3. Escolha o par com maior probabilidade (desempate: maior cobertura positiva)
4. Adicione esse par ao antecedente e restrinja o subconjunto
5. Repita até que a regra seja **perfeita** ($p = 1.0$) ou não haja mais atributos
6. Remova os exemplos cobertos e repita para gerar a próxima regra
7. Pare quando não houver mais exemplos da classe

In [6]:
def prism_rule(subset, target_class, target_col, features):
    """
    Gera UMA regra para target_class usando o algoritmo PRISM.
    Retorna (antecedente, exemplos_cobertos) ou (None, None) se não possível.
    """
    current = subset.copy()
    antecedent = []
    used_attrs = set()

    while True:
        # Contar positivos no subconjunto atual
        n_pos = (current[target_col] == target_class).sum()
        n_tot = len(current)

        if n_tot == 0 or n_pos == 0:
            return None, None

        # Se p = 1.0, regra perfeita
        if n_pos == n_tot:
            covered = current[current[target_col] == target_class]
            return antecedent, covered

        # Calcular p(class | attr = val) para todos os pares disponíveis
        best_p = -1
        best_cov = -1
        best_pair = None

        available = [f for f in features if f not in used_attrs]
        if not available:
            # Sem mais atributos: retorna regra impura (melhor esforço)
            covered = current[current[target_col] == target_class]
            return antecedent, covered

        for attr in available:
            for val in current[attr].unique():
                sub = current[current[attr] == val]
                n_sub_pos = (sub[target_col] == target_class).sum()
                n_sub_tot = len(sub)
                if n_sub_tot == 0:
                    continue
                p = n_sub_pos / n_sub_tot
                cov = n_sub_pos
                if (p > best_p) or (p == best_p and cov > best_cov):
                    best_p = p
                    best_cov = cov
                    best_pair = (attr, val)

        if best_pair is None:
            return None, None

        attr, val = best_pair
        antecedent.append((attr, val))
        used_attrs.add(attr)
        current = current[current[attr] == val]


def prism(df, target_col, features):
    """
    Executa o algoritmo PRISM completo para todas as classes.
    Retorna dicionário: classe -> lista de antecedentes (lista de pares).
    """
    classes = df[target_col].unique().tolist()
    all_rules = {}

    for cls in classes:
        rules = []
        remaining = df.copy()

        while True:
            # Verificar se ainda há exemplos da classe
            if (remaining[target_col] == cls).sum() == 0:
                break

            antecedent, covered = prism_rule(remaining, cls, target_col, features)

            if antecedent is None or covered is None or len(covered) == 0:
                break

            rules.append(antecedent)

            # Remover exemplos cobertos
            remaining = remaining.drop(index=covered.index)

        all_rules[cls] = rules

    return all_rules

print("Funções do algoritmo PRISM definidas.")

Funções do algoritmo PRISM definidas.

## 4. Executando o PRISM no Dataset de Gripe

In [7]:
rules = prism(df_clean, target, features)

print("=" * 60)
print("REGRAS GERADAS PELO ALGORITMO PRISM")
print("=" * 60)

total_rules = 0
for cls, cls_rules in rules.items():
    print(f"\n>>> Classe alvo: gripado = '{cls}'")
    if not cls_rules:
        print("  (nenhuma regra gerada)")
    for i, antecedent in enumerate(cls_rules, 1):
        cond = " AND ".join([f"{a} = {v}" for a, v in antecedent])
        print(f"  R{i}: IF {cond} THEN gripado = {cls}")
        total_rules += 1

print(f"\nTotal de regras geradas: {total_rules}")

============================================================
REGRAS GERADAS PELO ALGORITMO PRISM
============================================================

>>> Classe alvo: gripado = 'Sim'
  R1: IF horas_sono = 4 horas ou menos THEN gripado = Sim
  R2: IF viagem = Nuca AND alergia = Não THEN gripado = Sim
  R3: IF alergia = Muito AND ambientes_cheios = Não THEN gripado = Sim
  R4: IF alergia = Muito AND alimentacao = Não, raramente THEN gripado = Sim
  R5: IF alergia = Médio AND estresse = 3 THEN gripado = Sim
  R6: IF estresse = 5 AND alergia = Muito AND viagem = Poucas vezes por ano THEN gripado = Sim
  R7: IF lavagem_maos = 6 a 10 vezes AND alergia = Médio AND estresse = 4 THEN gripado = Sim
  R8: IF estresse = 5 AND lavagem_maos = 2 vezes ou menos AND atividade_fisica = Sim THEN gripado = Sim
  R9: IF viagem = Poucas vezes por ano AND estresse = 5 AND lavagem_maos = Mais de 10 vezes THEN gripado = Sim
  R10: IF viagem = Poucas vezes por ano AND estresse = 5 AND ambientes_cheios = Não THEN gripado = Sim
  R11: IF viagem = Poucas vezes por ano AND estresse = 5 AND alimentacao = Sim, a maior parte do tempo AND vacina = Sim THEN gripado = Sim
  R12: IF estresse = 4 AND lavagem_maos = 2 vezes ou menos AND horas_sono = mais de 6 horas THEN gripado = Sim
  R13: IF viagem = Poucas vezes por ano AND vacina = Não AND alergia = Muito THEN gripado = Sim
  R14: IF estresse = 2 AND alimentacao = Às vezes THEN gripado = Sim
  R15: IF estresse = 4 AND alergia = Pouco AND vacina = Sim AND horas_sono = mais de 6 horas THEN gripado = Sim
  R16: IF viagem = Poucas vezes por ano AND vacina = Não AND atividade_fisica = Não AND estresse = 4 THEN gripado = Sim
  R17: IF lavagem_maos = 6 a 10 vezes AND estresse = 2 AND vacina = Não THEN gripado = Sim
  R18: IF lavagem_maos = 3 a 5 vezes AND alergia = Não AND viagem = Poucas vezes por ano AND vacina = Não THEN gripado = Sim
  R19: IF lavagem_maos = 6 a 10 vezes AND atividade_fisica = Sim AND viagem = Nuca THEN gripado = Sim
  R20: IF lavagem_maos = 6 a 10 vezes AND atividade_fisica = Sim AND alimentacao = Às vezes AND alergia = Não THEN gripado = Sim
  R21: IF alergia = Pouco AND alimentacao = Não, raramente THEN gripado = Sim
  R22: IF lavagem_maos = 3 a 5 vezes AND vacina = Sim AND estresse = 5 AND horas_sono = mais de 6 horas THEN gripado = Sim
  R23: IF alergia = Pouco AND estresse = 4 AND alimentacao = Sim, a maior parte do tempo AND viagem = Nuca THEN gripado = Sim
  R24: IF alergia = Pouco AND atividade_fisica = Sim AND lavagem_maos = 6 a 10 vezes AND estresse = 5 THEN gripado = Sim
  R25: IF estresse = 4 AND alimentacao = Sim, a maior parte do tempo AND alergia = Pouco AND atividade_fisica = Sim AND viagem = Pelo menos uma vez por mês THEN gripado = Sim
  R26: IF viagem = Poucas vezes por ano AND alimentacao = Sim, a maior parte do tempo AND lavagem_maos = 3 a 5 vezes AND estresse = 5 THEN gripado = Sim
  R27: IF viagem = Poucas vezes por ano AND alimentacao = Sim, a maior parte do tempo AND lavagem_maos = 3 a 5 vezes AND horas_sono = entre 4 e 6 horas AND alergia = Pouco THEN gripado = Sim
  R28: IF viagem = Poucas vezes por ano AND alimentacao = Sim, a maior parte do tempo AND lavagem_maos = 3 a 5 vezes AND alergia = Não AND atividade_fisica = Não THEN gripado = Sim
  R29: IF estresse = 4 AND horas_sono = mais de 6 horas AND lavagem_maos = Mais de 10 vezes THEN gripado = Sim
  R30: IF lavagem_maos = 6 a 10 vezes AND estresse = 2 AND vacina = Sim AND ambientes_cheios = Sim AND viagem = Pelo menos uma vez por mês AND alergia = Médio AND horas_sono = mais de 6 horas AND atividade_fisica = Sim AND alimentacao = Sim, a maior parte do tempo THEN gripado = Sim
  R31: IF lavagem_maos = 6 a 10 vezes AND alergia = Pouco AND alimentacao = Às vezes AND horas_sono = mais de 6 horas THEN gripado = Sim
  R32: IF estresse = 4 AND viagem = Pelo menos uma vez por mês AND alergia = Médio THEN gripado = Sim
  R33: IF viagem = Poucas vezes por ano AND estresse = 5 AND alimentacao = Sim, a maior parte do tempo AND vacina = Não AND ambientes_cheios = Sim AND alergia = Não AND horas_sono = mais de 6 horas AND atividade_fisica = Sim AND lavagem_maos = 6 a 10 vezes THEN gripado = Sim
  R34: IF viagem = Poucas vezes por ano AND alimentacao = Sim, a maior parte do tempo AND lavagem_maos = 3 a 5 vezes AND vacina = Sim AND alergia = Médio THEN gripado = Sim
  R35: IF estresse = 4 AND lavagem_maos = 6 a 10 vezes AND alergia = Pouco AND vacina = Não AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND horas_sono = mais de 6 horas AND atividade_fisica = Sim AND alimentacao = Sim, a maior parte do tempo THEN gripado = Sim
  R36: IF alergia = Não AND estresse = 4 AND horas_sono = mais de 6 horas AND ambientes_cheios = Sim AND viagem = Pelo menos uma vez por mês THEN gripado = Sim
  R37: IF alergia = Não AND alimentacao = Às vezes AND lavagem_maos = Mais de 10 vezes AND ambientes_cheios = Sim THEN gripado = Sim
  R38: IF horas_sono = entre 4 e 6 horas AND estresse = 3 AND vacina = Não AND viagem = Poucas vezes por ano THEN gripado = Sim
  R39: IF lavagem_maos = 3 a 5 vezes AND alergia = Não AND estresse = 4 AND vacina = Sim AND ambientes_cheios = Sim AND viagem = Pelo menos uma vez por mês AND horas_sono = entre 4 e 6 horas AND atividade_fisica = Sim AND alimentacao = Às vezes THEN gripado = Sim
  R40: IF lavagem_maos = 3 a 5 vezes AND estresse = 3 AND alergia = Não AND atividade_fisica = Sim AND vacina = Não THEN gripado = Sim
  R41: IF vacina = Sim AND estresse = 5 AND alimentacao = Não, raramente AND lavagem_maos = 6 a 10 vezes THEN gripado = Sim
  R42: IF vacina = Sim AND lavagem_maos = 3 a 5 vezes AND estresse = 5 AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND alergia = Médio AND horas_sono = entre 4 e 6 horas AND atividade_fisica = Não AND alimentacao = Às vezes THEN gripado = Sim
  R43: IF vacina = Sim AND alergia = Pouco AND atividade_fisica = Sim AND lavagem_maos = 3 a 5 vezes AND horas_sono = mais de 6 horas THEN gripado = Sim
  R44: IF estresse = 4 AND alergia = Pouco AND vacina = Sim AND atividade_fisica = Sim AND lavagem_maos = Mais de 10 vezes THEN gripado = Sim
  R45: IF alergia = Não AND lavagem_maos = 3 a 5 vezes AND viagem = Poucas vezes por ano AND horas_sono = entre 4 e 6 horas AND vacina = Sim AND ambientes_cheios = Sim AND atividade_fisica = Sim AND alimentacao = Sim, a maior parte do tempo AND estresse = 3 THEN gripado = Sim
  R46: IF lavagem_maos = 6 a 10 vezes AND estresse = 4 AND alimentacao = Sim, a maior parte do tempo AND vacina = Sim AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND alergia = Não AND horas_sono = mais de 6 horas AND atividade_fisica = Sim THEN gripado = Sim

>>> Classe alvo: gripado = 'Não'
  R1: IF estresse = 1 THEN gripado = Não
  R2: IF viagem = Pelo menos uma vez por mês AND lavagem_maos = Mais de 10 vezes AND vacina = Sim THEN gripado = Não
  R3: IF viagem = Pelo menos uma vez por mês AND ambientes_cheios = Não AND horas_sono = mais de 6 horas THEN gripado = Não
  R4: IF alimentacao = Não, raramente AND vacina = Não AND alergia = Não THEN gripado = Não
  R5: IF lavagem_maos = Mais de 10 vezes AND estresse = 2 THEN gripado = Não
  R6: IF atividade_fisica = Não AND estresse = 2 AND alergia = Pouco THEN gripado = Não
  R7: IF lavagem_maos = Mais de 10 vezes AND viagem = Pelo menos uma vez por mês AND horas_sono = entre 4 e 6 horas THEN gripado = Não
  R8: IF estresse = 3 AND alergia = Pouco AND lavagem_maos = Mais de 10 vezes THEN gripado = Não
  R9: IF atividade_fisica = Não AND lavagem_maos = 6 a 10 vezes AND estresse = 3 THEN gripado = Não
  R10: IF viagem = Pelo menos uma vez por mês AND alergia = Muito AND vacina = Não THEN gripado = Não
  R11: IF atividade_fisica = Não AND viagem = Pelo menos uma vez por mês AND alimentacao = Sim, a maior parte do tempo THEN gripado = Não
  R12: IF lavagem_maos = Mais de 10 vezes AND alergia = Médio AND viagem = Nuca THEN gripado = Não
  R13: IF estresse = 4 AND alimentacao = Não, raramente AND atividade_fisica = Não THEN gripado = Não
  R14: IF alimentacao = Às vezes AND alergia = Pouco AND viagem = Nuca THEN gripado = Não
  R15: IF lavagem_maos = Mais de 10 vezes AND alergia = Médio AND horas_sono = entre 4 e 6 horas AND ambientes_cheios = Sim THEN gripado = Não
  R16: IF estresse = 3 AND lavagem_maos = 2 vezes ou menos AND vacina = Sim THEN gripado = Não
  R17: IF alergia = Pouco AND viagem = Nuca AND horas_sono = mais de 6 horas THEN gripado = Não
  R18: IF lavagem_maos = 3 a 5 vezes AND ambientes_cheios = Não AND alergia = Médio THEN gripado = Não
  R19: IF alergia = Pouco AND estresse = 3 AND atividade_fisica = Sim AND viagem = Pelo menos uma vez por mês THEN gripado = Não
  R20: IF alimentacao = Às vezes AND alergia = Pouco AND lavagem_maos = 3 a 5 vezes AND vacina = Não THEN gripado = Não
  R21: IF alimentacao = Às vezes AND lavagem_maos = 3 a 5 vezes AND alergia = Pouco AND horas_sono = entre 4 e 6 horas THEN gripado = Não
  R22: IF alergia = Não AND viagem = Pelo menos uma vez por mês AND estresse = 5 THEN gripado = Não
  R23: IF vacina = Sim AND estresse = 3 AND ambientes_cheios = Não AND alergia = Não THEN gripado = Não
  R24: IF vacina = Sim AND estresse = 3 AND viagem = Pelo menos uma vez por mês AND alergia = Muito THEN gripado = Não
  R25: IF estresse = 4 AND alergia = Muito AND atividade_fisica = Não THEN gripado = Não
  R26: IF estresse = 4 AND horas_sono = entre 4 e 6 horas AND alergia = Não AND alimentacao = Sim, a maior parte do tempo THEN gripado = Não
  R27: IF lavagem_maos = 6 a 10 vezes AND atividade_fisica = Não AND viagem = Nuca AND horas_sono = entre 4 e 6 horas THEN gripado = Não
  R28: IF alimentacao = Às vezes AND horas_sono = entre 4 e 6 horas AND alergia = Pouco AND lavagem_maos = 6 a 10 vezes THEN gripado = Não
  R29: IF estresse = 4 AND horas_sono = entre 4 e 6 horas AND alergia = Não AND lavagem_maos = 2 vezes ou menos THEN gripado = Não
  R30: IF alergia = Médio AND estresse = 5 AND alimentacao = Não, raramente AND lavagem_maos = 2 vezes ou menos THEN gripado = Não
  R31: IF estresse = 4 AND alergia = Pouco AND lavagem_maos = Mais de 10 vezes AND viagem = Poucas vezes por ano AND alimentacao = Sim, a maior parte do tempo THEN gripado = Não
  R32: IF horas_sono = mais de 6 horas AND lavagem_maos = 6 a 10 vezes AND alergia = Muito AND vacina = Sim THEN gripado = Não
  R33: IF lavagem_maos = 3 a 5 vezes AND alergia = Médio AND horas_sono = entre 4 e 6 horas AND atividade_fisica = Sim THEN gripado = Não
  R34: IF alergia = Não AND viagem = Pelo menos uma vez por mês AND horas_sono = entre 4 e 6 horas AND vacina = Não THEN gripado = Não
  R35: IF horas_sono = mais de 6 horas AND alergia = Médio AND estresse = 5 AND vacina = Não THEN gripado = Não
  R36: IF horas_sono = mais de 6 horas AND lavagem_maos = 6 a 10 vezes AND alergia = Médio AND vacina = Sim AND alimentacao = Às vezes THEN gripado = Não
  R37: IF estresse = 3 AND viagem = Poucas vezes por ano AND alergia = Não AND vacina = Sim AND alimentacao = Às vezes THEN gripado = Não
  R38: IF alimentacao = Sim, a maior parte do tempo AND estresse = 2 AND viagem = Pelo menos uma vez por mês AND vacina = Sim AND ambientes_cheios = Sim AND alergia = Médio AND horas_sono = mais de 6 horas AND atividade_fisica = Sim AND lavagem_maos = 6 a 10 vezes THEN gripado = Não
  R39: IF alergia = Não AND vacina = Sim AND lavagem_maos = 3 a 5 vezes AND viagem = Pelo menos uma vez por mês AND ambientes_cheios = Sim AND horas_sono = entre 4 e 6 horas AND atividade_fisica = Sim AND alimentacao = Às vezes AND estresse = 4 THEN gripado = Não
  R40: IF alimentacao = Sim, a maior parte do tempo AND estresse = 3 AND alergia = Pouco AND vacina = Não AND horas_sono = mais de 6 horas THEN gripado = Não
  R41: IF lavagem_maos = Mais de 10 vezes AND estresse = 3 AND atividade_fisica = Não AND viagem = Poucas vezes por ano THEN gripado = Não
  R42: IF estresse = 4 AND alergia = Pouco AND lavagem_maos = 6 a 10 vezes AND vacina = Não AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND horas_sono = mais de 6 horas AND atividade_fisica = Sim AND alimentacao = Sim, a maior parte do tempo THEN gripado = Não
  R43: IF alergia = Não AND lavagem_maos = 6 a 10 vezes AND alimentacao = Sim, a maior parte do tempo AND viagem = Poucas vezes por ano AND atividade_fisica = Sim AND ambientes_cheios = Sim AND horas_sono = mais de 6 horas AND vacina = Sim AND estresse = 4 THEN gripado = Não
  R44: IF lavagem_maos = 3 a 5 vezes AND alergia = Médio AND horas_sono = entre 4 e 6 horas AND viagem = Poucas vezes por ano AND vacina = Sim AND ambientes_cheios = Sim AND atividade_fisica = Não AND alimentacao = Às vezes AND estresse = 5 THEN gripado = Não
  R45: IF lavagem_maos = Mais de 10 vezes AND vacina = Não AND horas_sono = entre 4 e 6 horas AND atividade_fisica = Sim THEN gripado = Não
  R46: IF alimentacao = Sim, a maior parte do tempo AND alergia = Não AND estresse = 5 AND horas_sono = mais de 6 horas AND vacina = Não AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND atividade_fisica = Sim AND lavagem_maos = 6 a 10 vezes THEN gripado = Não
  R47: IF lavagem_maos = 3 a 5 vezes AND alimentacao = Sim, a maior parte do tempo AND alergia = Médio AND vacina = Não AND horas_sono = mais de 6 horas AND estresse = 4 THEN gripado = Não
  R48: IF estresse = 3 AND horas_sono = entre 4 e 6 horas AND vacina = Sim AND atividade_fisica = Sim AND ambientes_cheios = Sim AND viagem = Poucas vezes por ano AND alergia = Não AND alimentacao = Sim, a maior parte do tempo AND lavagem_maos = 3 a 5 vezes THEN gripado = Não

Total de regras geradas: 94

## 5. Avaliação das Regras

Vamos avaliar cada regra gerada calculando:
- **Cobertura**: quantas instâncias são cobertas pelo antecedente
- **Acurácia da regra**: proporção de instâncias cobertas que têm a classe correta
- **Cobertura positiva**: instâncias cobertas com a classe alvo correta

In [9]:
def apply_rule(df, antecedent):
    """Retorna máscara booleana das instâncias cobertas pela regra."""
    mask = pd.Series([True] * len(df), index=df.index)
    for attr, val in antecedent:
        mask &= (df[attr] == val)
    return mask

print(f"{'Classe':<8} {'#':<4} {'Regra (resumida)':<65} {'Cob':>5} {'Prec':>7}")
print("-" * 95)

for cls, cls_rules in rules.items():
    for i, antecedent in enumerate(cls_rules, 1):
        mask = apply_rule(df_clean, antecedent)
        covered = mask.sum()
        if covered == 0:
            prec = 0.0
        else:
            prec = (df_clean.loc[mask, target] == cls).sum() / covered
        cond = " AND ".join([f"{a}={v}" for a, v in antecedent])
        cond_short = cond[:62] + "..." if len(cond) > 65 else cond
        print(f"{cls:<8} R{i:<3} {cond_short:<65} {covered:>5} {prec:>7.2%}")

Classe   #    Regra (resumida)                                                    Cob    Prec
-----------------------------------------------------------------------------------------------
Sim      R1   horas_sono=4 horas ou menos                                           4 100.00%
Sim      R2   viagem=Nuca AND alergia=Não                                           6 100.00%
Sim      R3   alergia=Muito AND ambientes_cheios=Não                                2 100.00%
Sim      R4   alergia=Muito AND alimentacao=Não, raramente                          2 100.00%
Sim      R5   alergia=Médio AND estresse=3                                          6 100.00%
Sim      R6   estresse=5 AND alergia=Muito AND viagem=Poucas vezes por ano          6 100.00%
Sim      R7   lavagem_maos=6 a 10 vezes AND alergia=Médio AND estresse=4           10 100.00%
Sim      R8   estresse=5 AND lavagem_maos=2 vezes ou menos AND atividade_fis...     5 100.00%
Sim      R9   viagem=Poucas vezes por ano AND estresse=5 AND lavagem_maos=Ma...     3 100.00%
Sim      R10  viagem=Poucas vezes por ano AND estresse=5 AND ambientes_cheio...     1 100.00%
Sim      R11  viagem=Poucas vezes por ano AND estresse=5 AND alimentacao=Sim...     7 100.00%
Sim      R12  estresse=4 AND lavagem_maos=2 vezes ou menos AND horas_sono=ma...     3 100.00%
Sim      R13  viagem=Poucas vezes por ano AND vacina=Não AND alergia=Muito          5 100.00%
Sim      R14  estresse=2 AND alimentacao=Às vezes                                   5 100.00%
Sim      R15  estresse=4 AND alergia=Pouco AND vacina=Sim AND horas_sono=mai...     2 100.00%
Sim      R16  viagem=Poucas vezes por ano AND vacina=Não AND atividade_fisic...     5 100.00%
Sim      R17  lavagem_maos=6 a 10 vezes AND estresse=2 AND vacina=Não               1 100.00%
Sim      R18  lavagem_maos=3 a 5 vezes AND alergia=Não AND viagem=Poucas vez...     6 100.00%
Sim      R19  lavagem_maos=6 a 10 vezes AND atividade_fisica=Sim AND viagem=...     2 100.00%
Sim      R20  lavagem_maos=6 a 10 vezes AND atividade_fisica=Sim AND aliment...     5 100.00%
Sim      R21  alergia=Pouco AND alimentacao=Não, raramente                          3 100.00%
Sim      R22  lavagem_maos=3 a 5 vezes AND vacina=Sim AND estresse=5 AND hor...     5 100.00%
Sim      R23  alergia=Pouco AND estresse=4 AND alimentacao=Sim, a maior part...     1 100.00%
Sim      R24  alergia=Pouco AND atividade_fisica=Sim AND lavagem_maos=6 a 10...     2 100.00%
Sim      R25  estresse=4 AND alimentacao=Sim, a maior parte do tempo AND ale...     2 100.00%
Sim      R26  viagem=Poucas vezes por ano AND alimentacao=Sim, a maior parte...     7 100.00%
Sim      R27  viagem=Poucas vezes por ano AND alimentacao=Sim, a maior parte...     3 100.00%
Sim      R28  viagem=Poucas vezes por ano AND alimentacao=Sim, a maior parte...     2 100.00%
Sim      R29  estresse=4 AND horas_sono=mais de 6 horas AND lavagem_maos=Mai...     5 100.00%
Sim      R30  lavagem_maos=6 a 10 vezes AND estresse=2 AND vacina=Sim AND am...     2  50.00%
Sim      R31  lavagem_maos=6 a 10 vezes AND alergia=Pouco AND alimentacao=Às...     3 100.00%
Sim      R32  estresse=4 AND viagem=Pelo menos uma vez por mês AND alergia=M...     6 100.00%
Sim      R33  viagem=Poucas vezes por ano AND estresse=5 AND alimentacao=Sim...     2  50.00%
Sim      R34  viagem=Poucas vezes por ano AND alimentacao=Sim, a maior parte...     1 100.00%
Sim      R35  estresse=4 AND lavagem_maos=6 a 10 vezes AND alergia=Pouco AND...     3  66.67%
Sim      R36  alergia=Não AND estresse=4 AND horas_sono=mais de 6 horas AND ...     2 100.00%
Sim      R37  alergia=Não AND alimentacao=Às vezes AND lavagem_maos=Mais de ...     2 100.00%
Sim      R38  horas_sono=entre 4 e 6 horas AND estresse=3 AND vacina=Não AND...     5 100.00%
Sim      R39  lavagem_maos=3 a 5 vezes AND alergia=Não AND estresse=4 AND va...     2  50.00%
Sim      R40  lavagem_maos=3 a 5 vezes AND estresse=3 AND alergia=Não AND at...     2 100.00%
Sim      R41  vacina=Sim AND estresse=5 AND alimentacao=Não, raramente AND l...     1 100.00%
Sim      R42  vacina=Sim AND lavagem_maos=3 a 5 vezes AND estresse=5 AND amb...     2  50.00%
Sim      R43  vacina=Sim AND alergia=Pouco AND atividade_fisica=Sim AND lava...     2 100.00%
Sim      R44  estresse=4 AND alergia=Pouco AND vacina=Sim AND atividade_fisi...     1 100.00%
Sim      R45  alergia=Não AND lavagem_maos=3 a 5 vezes AND viagem=Poucas vez...     2  50.00%
Sim      R46  lavagem_maos=6 a 10 vezes AND estresse=4 AND alimentacao=Sim, ...     2  50.00%
Não      R1   estresse=1                                                            2 100.00%
Não      R2   viagem=Pelo menos uma vez por mês AND lavagem_maos=Mais de 10 ...     7 100.00%
Não      R3   viagem=Pelo menos uma vez por mês AND ambientes_cheios=Não AND...     6 100.00%
Não      R4   alimentacao=Não, raramente AND vacina=Não AND alergia=Não             4 100.00%
Não      R5   lavagem_maos=Mais de 10 vezes AND estresse=2                          2 100.00%
Não      R6   atividade_fisica=Não AND estresse=2 AND alergia=Pouco                 2 100.00%
Não      R7   lavagem_maos=Mais de 10 vezes AND viagem=Pelo menos uma vez po...     4 100.00%
Não      R8   estresse=3 AND alergia=Pouco AND lavagem_maos=Mais de 10 vezes        3 100.00%
Não      R9   atividade_fisica=Não AND lavagem_maos=6 a 10 vezes AND estresse=3     4 100.00%
Não      R10  viagem=Pelo menos uma vez por mês AND alergia=Muito AND vacina...     3 100.00%
Não      R11  atividade_fisica=Não AND viagem=Pelo menos uma vez por mês AND...     4 100.00%
Não      R12  lavagem_maos=Mais de 10 vezes AND alergia=Médio AND viagem=Nuca       1 100.00%
Não      R13  estresse=4 AND alimentacao=Não, raramente AND atividade_fisica...     3 100.00%
Não      R14  alimentacao=Às vezes AND alergia=Pouco AND viagem=Nuca                1 100.00%
Não      R15  lavagem_maos=Mais de 10 vezes AND alergia=Médio AND horas_sono...     4 100.00%
Não      R16  estresse=3 AND lavagem_maos=2 vezes ou menos AND vacina=Sim           2 100.00%
Não      R17  alergia=Pouco AND viagem=Nuca AND horas_sono=mais de 6 horas          1 100.00%
Não      R18  lavagem_maos=3 a 5 vezes AND ambientes_cheios=Não AND alergia=...     2 100.00%
Não      R19  alergia=Pouco AND estresse=3 AND atividade_fisica=Sim AND viag...     2 100.00%
Não      R20  alimentacao=Às vezes AND alergia=Pouco AND lavagem_maos=3 a 5 ...     3 100.00%
Não      R21  alimentacao=Às vezes AND lavagem_maos=3 a 5 vezes AND alergia=...     3 100.00%
Não      R22  alergia=Não AND viagem=Pelo menos uma vez por mês AND estresse=5      4 100.00%
Não      R23  vacina=Sim AND estresse=3 AND ambientes_cheios=Não AND alergia...     3 100.00%
Não      R24  vacina=Sim AND estresse=3 AND viagem=Pelo menos uma vez por mê...     1 100.00%
Não      R25  estresse=4 AND alergia=Muito AND atividade_fisica=Não                 1 100.00%
Não      R26  estresse=4 AND horas_sono=entre 4 e 6 horas AND alergia=Não AN...     1 100.00%
Não      R27  lavagem_maos=6 a 10 vezes AND atividade_fisica=Não AND viagem=...     1 100.00%
Não      R28  alimentacao=Às vezes AND horas_sono=entre 4 e 6 horas AND aler...     1 100.00%
Não      R29  estresse=4 AND horas_sono=entre 4 e 6 horas AND alergia=Não AN...     1 100.00%
Não      R30  alergia=Médio AND estresse=5 AND alimentacao=Não, raramente AN...     1 100.00%
Não      R31  estresse=4 AND alergia=Pouco AND lavagem_maos=Mais de 10 vezes...     1 100.00%
Não      R32  horas_sono=mais de 6 horas AND lavagem_maos=6 a 10 vezes AND a...     2 100.00%
Não      R33  lavagem_maos=3 a 5 vezes AND alergia=Médio AND horas_sono=entr...     1 100.00%
Não      R34  alergia=Não AND viagem=Pelo menos uma vez por mês AND horas_so...     4 100.00%
Não      R35  horas_sono=mais de 6 horas AND alergia=Médio AND estresse=5 AN...     1 100.00%
Não      R36  horas_sono=mais de 6 horas AND lavagem_maos=6 a 10 vezes AND a...     1 100.00%
Não      R37  estresse=3 AND viagem=Poucas vezes por ano AND alergia=Não AND...     2 100.00%
Não      R38  alimentacao=Sim, a maior parte do tempo AND estresse=2 AND via...     2  50.00%
Não      R39  alergia=Não AND vacina=Sim AND lavagem_maos=3 a 5 vezes AND vi...     2  50.00%
Não      R40  alimentacao=Sim, a maior parte do tempo AND estresse=3 AND ale...     2 100.00%
Não      R41  lavagem_maos=Mais de 10 vezes AND estresse=3 AND atividade_fis...     1 100.00%
Não      R42  estresse=4 AND alergia=Pouco AND lavagem_maos=6 a 10 vezes AND...     3  33.33%
Não      R43  alergia=Não AND lavagem_maos=6 a 10 vezes AND alimentacao=Sim,...     2  50.00%
Não      R44  lavagem_maos=3 a 5 vezes AND alergia=Médio AND horas_sono=entr...     2  50.00%
Não      R45  lavagem_maos=Mais de 10 vezes AND vacina=Não AND horas_sono=en...     5 100.00%
Não      R46  alimentacao=Sim, a maior parte do tempo AND alergia=Não AND es...     2  50.00%
Não      R47  lavagem_maos=3 a 5 vezes AND alimentacao=Sim, a maior parte do...     2 100.00%
Não      R48  estresse=3 AND horas_sono=entre 4 e 6 horas AND vacina=Sim AND...     2  50.00%

## 6. Classificação com as Regras Geradas

Aplicamos as regras ao dataset completo para prever a classe. Uma instância é classificada pela **primeira regra** que a cobre (ordenadas por classe e índice).  
Se nenhuma regra cobrir a instância, a classe mais frequente (default) é atribuída.

In [10]:
def predict_prism(df, rules, target_col, default_class=None):
    """Aplica regras PRISM e retorna série de predições."""
    if default_class is None:
        default_class = df[target_col].value_counts().idxmax()

    predictions = pd.Series([default_class] * len(df), index=df.index)

    # Aplicar regras em ordem inversa para que as primeiras regras tenham prioridade
    for cls, cls_rules in rules.items():
        for antecedent in reversed(cls_rules):
            mask = apply_rule(df, antecedent)
            predictions[mask] = cls

    return predictions

y_pred = predict_prism(df_clean, rules, target)
y_true = df_clean[target]

accuracy = (y_pred == y_true).mean()
print(f"Acurácia geral no conjunto de treino: {accuracy:.2%}")
print(f"Instâncias totais: {len(y_true)}")
print(f"Acertos: {(y_pred == y_true).sum()}")
print(f"Erros: {(y_pred != y_true).sum()}")

Acurácia geral no conjunto de treino: 95.68%
Instâncias totais: 185
Acertos: 177
Erros: 8